# On push to `main`: run builds and deploy

when:
  - event: push
    branch: main

# Adapted from https://codeberg.org/Codeberg-CI/examples/src/branch/main/Python/mkdocs.yml
steps:
  build-pages:
    # Build the site in /public with Zola
    name: Build
    # image: ghcr.io/getzola/zola:v0.17.2
    # image: alpine:3
    image: jauderho/zola:v0.17.2
    commands:
      # - curl -s -L https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - zola build
      - git switch --orphan pages
      - mv public/* .

  deploy-pages:
    # Push the resulting files
    name: Deploy
    image: appleboy/drone-git-push
    settings:
      branch: main
      # remote: git@codeberg.org:averagehelper/pages.git
      remote: https://${CODEBERG_ACCESS_TOKEN}codeberg.org:averagehelper/pages.git
      force: true
      commit: true
      # ssh_key:
      #   from_secret: codeberg_access_token
