# On push to `main`: run builds and deploy

when:
  - event: push
    branch: main

# Adapted from https://codeberg.org/Codeberg-CI/examples/src/branch/main/Python/mkdocs.yml
steps:
  build-pages:
    # Build the site in /public with Zola
    # and add the .domains file for Codeberg Pages
    name: Build
    image: ubuntu:noble
    commands:
      - apt-get update -y
      - apt-get install -y sudo curl git
      - curl -s -L https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - zola build
      - git switch --orphan pages
      - mv public/* .
      - echo 'blog.average.name\naveragehelper.codeberg.page\n' > .domains

  deploy-pages:
    # Push the resulting files
    name: Deploy
    image: appleboy/drone-git-push
    settings:
      branch: pages
      remote:
        from_secret: remote # Format: https://${CI_REPO_OWNER}:${CODEBERG_ACCESS_TOKEN}@codeberg.org/AverageHelper/pages.git
      force: true
      commit: true
