name: "Automatic build"
on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' # only on PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test build
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          CHECK_LINKS: true

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only on push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Publishing to the same repo, so default token should work
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
